spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

api.security.token.secret=${JWT_SECRET}

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DIALETO POSTGRES
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.expirationMs=3600000

logging.file.name=logs/api-clinica.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] [usuario = %X{usuario}] %logger{36} - %msg%n
logging.level.com.clinica.api=INFO